name: Development
description: File a development task.
title: "[DEV]: "
labels: ["development"]
body:
  - type: markdown
    attributes
      value: |
        Thanks for taking the time to fill out this development task!
  - type: input
    id: file
    attributes:
      label: Task [REQUIRED]
      description: What is the task to be completed?
      placeholder: Develop code for ESP32 serial...
    validations:
      required: true
  - type: input
    id: file
    attributes:
      label: Future [REQUIRED]
      description: What will be done after completion?
      placeholder: Develop code for ESP32 serial...
    validations:
      required: true